# Site settings
title: Luís Fonseca
email: luis.fonseca ecb.europa.eu
description: Personal webpage of Luís Fonseca, Economist at the European Central Bank
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://luispfonseca.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: luispfonseca
github_username:  luispfonseca
google_scholar_id: oB3EgRQAAAAJ
ideas_repec_id: pfo283
orcid_id: 0000-0001-6168-3501

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Economist"
excerpt_separator: "<!--more-->"

# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""